from core.exceptions.base import CoreError


class BadCredentialsError(CoreError):
    pass
